# Generated by Django 3.0.6 on 2020-05-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upload_picture', models.ImageField(upload_to='pics')),
                ('upload_card', models.FileField(upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
    ]
